version: '3'

services:
  welcome:
    build:
      context: ./welcome
    ports:
      - "8080:80"

  logisimweb:
    build:
      context: ./LogisimWeb
    ports:
      - "8000:80"

  mipstranslator:
    build:
      context: ./MIPSTranslator
    ports:
      - "8001:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - welcome
      - logisimweb
      - mipstranslator
