version: '3'

services:
  logisimweb:
    build:
      context: ./LogisimWeb
    ports:
      - "8000:80" 

  mipstranslator:
    build:
      context: ./MIPSTranslator
    ports:
      - "8001:80"  

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./welcome:/usr/share/nginx/html 
    ports:
      - "8081:80"  
    depends_on:
      - logisimweb
      - mipstranslator